name: CI

on: [push]

jobs:
  build:
    runs-on: macos-12
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

    - name: Switch to Xcode 14.2
      run: sudo xcode-select -s /Applications/Xcode_14.2.app

    - name: Show Build Version
      run: xcodebuild -version

    - name: build and test
      run: xcodebuild clean test -scheme 'MPCF-TestRunner-ios' -destination 'platform=iOS Simulator,OS=16.0,name=iPhone 11' -showBuildTimingSummary
