name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: '13.0'

    - name: Install Dependencies
      run: |
        bundle install

    - name: Build and Test
      run: |
        xcodebuild -workspace SPLYT.xcworkspace \
                   -scheme SPLYT \
                   -testPlan AllTests \
                   -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 15' \
                   -configuration Debug \
                   clean test | xcpretty
